global:
  scrape_interval: 5s
  external_labels:
    monitor: "fastapi-monitor"

rule_files:
  - alert.rules.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "fast-api"
    static_configs:
      - targets: ["fastapi:8000"]